### ISSUE TITLE
Greedy directive highlighting

### ISSUE THREAD

**Issue by anntzer** [habamax/vim-rst#11]
In
```rst
:directive:`contents`

:directive:`contents` and then some more text: but with a colon
```
vim-rst currently incorrectly highlights the second line all the way to the last colon.

**Comment by habamax** [comment]
Pls check master

**Comment by habamax** [comment]
I did a fix from a new laptop and looks like line endings now an issue...

**Comment by habamax** [comment]
Or not, tried it in WSL, works ok. :)

**Comment by anntzer** [comment]
Thanks, fixed :)
