### ISSUE TITLE
`.. function:: breakpoint(*args, **kws)` causes following paragraphs to be italicized

### ISSUE THREAD

**Issue by nedbat** [habamax/vim-rst#16]
The CPython docs use `.. function::` directives.  The star and double-star are incorrectly interpreted as text styling and affect the paragraphs that follow:

<img width="744" alt="image" src="https://github.com/habamax/vim-rst/assets/23789/d4674075-342a-4e8b-ab2b-d4d91d3b74d1">

I tried adding backslashes in the directive to escape the stars, but then the backslashes are rendered in the output.

**Comment by habamax** [comment]
What about this:

![image](https://github.com/habamax/vim-rst/assets/234774/276bb8f8-135f-4be2-be0f-62b0d26cec48)

or this:

![image](https://github.com/habamax/vim-rst/assets/234774/ff078614-e3df-4421-b6ba-7af5cb97d902)

**Comment by habamax** [comment]
Actually `rst2html` kind of warns about bad formatting otherwise:

![image](https://github.com/habamax/vim-rst/assets/234774/958f27d5-ca1c-4511-a4d3-7a21af6bf42c)

![image](https://github.com/habamax/vim-rst/assets/234774/5674bf54-79f6-4ae2-b41c-a02690c6133b)

Here I have used note admonition as I don't have `function` directive.

**Comment by habamax** [comment]
With escapes it looks ok:

![image](https://github.com/habamax/vim-rst/assets/234774/0509449d-a7ff-4c7a-9b95-f7e3f0e3bf39)

**Comment by nedbat** [comment]
> Funnily enough on their web they have issues with italic text as well :)

Sorry, what URL is that? If it's a GitHub rendering, then it's another example of a tool not understanding this detail of rst syntax.

**Comment by habamax** [comment]
@nedbat that is https://devguide.python.org/documentation/markup/#additional-markup-constructs

Will have a look into handling those constructs.

**Comment by nedbat** [comment]
Thanks, looks great! (I added some markup to words to see that italics and bold were still working outside of these directives):
<img width="611" alt="image" src="https://github.com/habamax/vim-rst/assets/23789/7c8aeb9b-f1b1-45c9-9e48-5ee74fca5d09">

**Comment by nedbat** [comment]
Hmm, looks like there are more directives to add:
<img width="640" alt="image" src="https://github.com/habamax/vim-rst/assets/23789/e8f33873-1369-4f71-8b92-55ce2169f7f3">

I would take a stab at a pull request, but I don't write syntax rules, so I'm sure I would get it wrong.  Can I help in some way?

**Comment by habamax** [comment]
Hi @nedbat,

Could you check latest commit? I have added 2 more python blocks `c:type` and `c:member`:

https://github.com/habamax/vim-rst/blob/master/syntax/rst.vim#L240-L240

![image](https://github.com/habamax/vim-rst/assets/234774/e252db32-b87b-450d-bd47-f94de0ea31f8)

**Comment by nedbat** [comment]
@habamax My hero, as always, thanks!

**Comment by habamax** [comment]
Closing for now
