### ISSUE TITLE
Weird lists indentation when using gggqG

### ISSUE THREAD

**Issue by ubaldot** [habamax/vim-rst#19]
If I use `gggqG`, lists indentation got mad.  
For example, from the following:

```
#.  potato
#.  banana
#. pineapple
#.  cocumber
```

I have the following result:

```
#.  potato
   #.  banana
      #. pineapple
         #.  cocumber
```
after I `gggqG`.

**Comment by habamax** [comment]
I can't reproduce it.

And the indentation part of this plugin has nothing to do with `gq` formatting...

[![asciicast](https://asciinema.org/a/yoh2cfeukUpGcjIlhn92MUKau.svg)](https://asciinema.org/a/yoh2cfeukUpGcjIlhn92MUKau)

**Comment by ubaldot** [comment]
Thanks!

Hum, interestingly enough when you run `gggqG` in your case it messes up the file in a different way. 
Btw, should you disable the bundled indent plugin to use this one? 

I also have found [this](https://vi.stackexchange.com/questions/16190/why-does-the-rst-filetype-automatically-indent-subsequent-list-items).

**Comment by habamax** [comment]
> Hum, interestingly enough when you run gggqG in your case it messes up the file in a different way.

gggqG runs internal formatter (or external if it is defined) for the whole buffer. vim-rst doesn't define or redefine `formatprg`/`formatexpr` for that. So basically it messes up restructured text buffer.

> Btw, should you disable the bundled indent plugin to use this one?

Well, if plugin is correctly installed then no, you don't have to disable bundled plugin.

> I also have found [this](https://vi.stackexchange.com/questions/16190/why-does-the-rst-filetype-automatically-indent-subsequent-list-items).

This is unrelated to my plugin, it didn't exist back then.
