### ISSUE TITLE
Pattern delimiter not found?

### ISSUE THREAD

**Issue by nedbat** [habamax/vim-rst#2]
```
line   23:
E401: Pattern delimiter not found: /^\s*\d\+[\]:.)}\t \ze\s\+/ contains=rstLineBlock
```
Vim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 24 2021 14:13:28)
macOS version - x86_64
Included patches: 1-3455
```

**Comment by habamax** [comment]
What is your `verbose set formatlistpat?` ?

**Comment by habamax** [comment]
I have updated highlighting to use separate variable for listitems... It might help, but still I wonder what happened to `formatlistpat` :)

**Comment by nedbat** [comment]
```
:verbose set formatlistpat?
formatlistpat=^\s*\d\+[\]:.)}\t ]\s*
```

**Comment by habamax** [comment]
yeah, so it is clearly not using formatlistpat from this plugin

**Comment by habamax** [comment]
ftplugin sets it to `formatlistpat=^\s*\%(\%([-+*]\)\|\%(\d\+[.)]\)\|\%((\d\+)\)\|\%(\%(\a\|#\)[.)]\)\|\%((\%(\a\|#\))\)\|\%(|\)\)\s\+`

https://github.com/habamax/vim-rst/blob/b8c8844fd3b93220b59ee8078735d2e7ab8da206/ftplugin/rst.vim#L21-L35

**Comment by habamax** [comment]
anyway, could you try the latest version? It at least should not error now.
