### ISSUE TITLE
Asterisk overlines get marked as emphasis

### ISSUE THREAD

**Issue by nedbat** [habamax/vim-rst#3]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/23789/139724905-5319efe9-e954-4e1f-b39c-3753b8e087d2.png">

The top line of stars has highlights rstDelimiter on the outer stars, rstStrongEmphasis on the inner ones.  The lower line of stars has rstSectionDelimiter.

**Comment by habamax** [comment]
Nice catch, thank you!

**Comment by habamax** [comment]
Should be fixed, could you check it?

**Comment by nedbat** [comment]
Fixed! :)
