### ISSUE TITLE
Comments nested in directives are not correctly ended

### ISSUE THREAD

**Issue by anntzer** [habamax/vim-rst#4]
```rst
.. directive::

   normal contents

   .. a comment

   this gets mishighlighted as a comment too
```

See https://github.com/marshallward/vim-restructuredtext/pull/73 for a proposed fix; feel free to take over my patch to this repo.

**Comment by habamax** [comment]
I have spent half a day already with exact same issue (what a coincidence :) )

Current approach of region start/end (which is basically the same as built-in has) is kind of limited as there is no way to find out an indent of the ExDirective as it is contained in a regular match (or rather `nextgroup` ed).

I am planning to completely redo ExDirective highlighting which should handle this issue:

![image](https://user-images.githubusercontent.com/234774/139838986-713119bd-2254-48d5-a2cc-827c606851e2.png)

**Comment by habamax** [comment]
And what I can't figure out -- how can I (if it possible at all) highlight matched region start differently.

For now it looks like all ex directives would be highlighted uniformly (no separate `..` and directive name highlighting)

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/139839317-53b42205-d75d-42ff-b5d3-80ed7b347652.png)

**Comment by habamax** [comment]
Merged. Could you please test master?

I hope I didn't break too much :).

Now embedded directives should work. The "drawback" is that I can't highlight parts of the directive definition differently now.

**Comment by anntzer** [comment]
Yup, it works for me, thanks!

Just as curiosity, is there a specific reason you decided not to contribute your improvements to the "official" rst plugin?  I have contributed a few patches there and found the maintainer reasonably responsive, so it seems a bit a pity to split the ecosystem.

**Comment by habamax** [comment]
> Yup, it works for me, thanks!

Welcome! It bothered me too :)

> Just as curiosity, is there a specific reason you decided not to contribute your improvements to the "official" rst plugin? 

It is just a freedom to do what I think suits me best with syntax definitions + highlighting, indentation, compilers and mappings (which blend into vim as `]]` and `[[` and some more "turned-off by default" I want to introduce).

> I have contributed a few patches there and found the maintainer reasonably responsive, so it seems a bit a pity to split the ecosystem.

I would be bound to the way bundled rst is implemented and to provide massive changes, I believe, a lot of communications would have to be done, explaining the reasoning of why we need to drop backward compatibility and yada yada. 

Or not. I don't know for sure, just my assumptions.

As for ecosystem split, I don't think it is a problem to have different approaches to the same problem.

**Comment by anntzer** [comment]
That's fine, good luck for your efforts :-)
