### ISSUE TITLE
Support :make variant/option that renders to a temporary file and opens a webbrowser to display it?

### ISSUE THREAD

**Issue by anntzer** [habamax/vim-rst#5]
Your :make currently writes the html output next to the rst file.  I have personally found it useful to write instead to a temporary directory, and immediately display the result in a webbrowser.  See https://github.com/marshallward/vim-restructuredtext/issues/62 for the implementation I currently use, although variants are certainly possible.  Perhaps this behavior can be configured with a variable?

**Comment by habamax** [comment]
Probably. I for now use :make and a simple mapping that opens generated html in a browser.

**Comment by anntzer** [comment]
If you can suggest a mapping implementation that would be nice too.

**Comment by habamax** [comment]
```
" Open filename in an OS
func! OSopen(url) abort
    let url = a:url
    if exists("$WSLENV")
        lcd /mnt/c
        let cmd = ":silent !cmd.exe /C start"
        if filereadable(a:url)
            let url = os#wsl_to_windows_path(a:url)
        endif
    elseif has("win32") || has("win32unix")
        let cmd = ':silent !start'
    elseif executable('xdg-open')
        let cmd = ":silent !xdg-open"
    elseif executable('open')
        let cmd = ":silent !open"
    else
        echohl Error
        echomsg "Can't find proper opener for an URL!"
        echohl None
        return
    endif

    try
        echom cmd . ' "' . url . '"'
        exe cmd . ' "' . url . '"'
    catch
        echohl Error
        echomsg v:exception
        echohl None
    finally
        if exists("$WSLENV") | lcd - | endif
        redraw!
    endtry
endfunc


command -buffer RSTViewHtml :call OSopen(expand("%:p:r").'.html')
nnoremap <buffer> goh :RSTViewHtml<CR>
```

**Comment by anntzer** [comment]
Ah, thanks, I'll play with that.  (For the OS-dependent side, perhaps you can use `python -mwebbrowser` instead -- if rst2html5 works, you probably have a python in your path.)

**Comment by habamax** [comment]
I wish there was webbrowser extension, like `Asciidoctor.js Live Preview` that would render plain `rst` file as html.

![image](https://user-images.githubusercontent.com/234774/140648590-727348b2-89c1-44b2-9411-9c48f322b5cb.png)

**Comment by habamax** [comment]
I was thinking about it the other day and decided not to add it.


One can add following snippet into their `~/.vim/after/ftplugin/rst.vim` to get desired/tailored behavior:

```vim
  func! s:rst_view() abort
    let output = tempname() . '.html'

    call system(printf("%s %s %s %s",
          \ "rst2html5.py",
          \ " --input-encoding=utf8 --stylesheet-path=minimal.css,responsive.css",
          \ shellescape(expand("%:p")),
          \ output
          \ ))

    " Comment/Uncomment what is appropriate
    " Windows
    exe ':silent !start ' . output
    " OSX
    " exe ':silent !xdg-open ' . output
    " Linux
    " exe ':silent !open ' . output
  endfunc

  command! -buffer RSTView call s:rst_view()
```
