### ISSUE TITLE
Incorrect inline markup recognition

### ISSUE THREAD

**Issue by anntzer** [habamax/vim-rst#6]
Currently, vim-rst does not recognize the closing double-backquotes in
```rst
``code``-like thing.
```
and thus highlights everything as code.  One can check with rst2html5 that the closing backquotes indeed work; this is also specced by item (7) of https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#inline-markup-recognition-rules ("Inline markup end-strings must end a text block or be immediately followed by (...) one of the ASCII characters `-` (...)").

**Comment by habamax** [comment]
yep, I have forgot to add `-` there.

![image](https://user-images.githubusercontent.com/234774/140612062-873de384-916f-4d6e-9eeb-16552332b953.png)

**Comment by anntzer** [comment]
Thanks for the quick fix!

**Comment by habamax** [comment]
welcome!

There was a breaking change wrt to syntax includes -- now by default nothing is included, one should add languages to a `g:rst_syntax_code_list` dictionary in vimrc.

Plus try `vie`, `vae` with directives and sections...
