### ISSUE TITLE
Substitution definitions not recognized when they occur on separate lines

### ISSUE THREAD

**Issue by anntzer** [habamax/vim-rst#7]
```rst
|linkimage-bad|

.. |linkimage-bad|
   image:: https://img.shields.io/badge/hello-world-brightgreen
   :target: https://shields.io/

|linkimage-good|

.. |linkimage-good| image:: https://img.shields.io/badge/hello-world-brightgreen
   :target: https://shields.io/
```

Currently, vim-rst highlights the first instance as if it was a comment.

Admittedly, it is not entirely clear to me whether the spec states anything on the allowability of a newline before the directive, and it looks like github's highlighter is also confused, but in practice docutils does allow it.

**Comment by habamax** [comment]
Should be fixed:
![image](https://user-images.githubusercontent.com/234774/140636155-d3a64a40-1ad4-4f5c-bc12-4fb08ab69865.png)

**Comment by anntzer** [comment]
Thanks for the quick fix!

**Comment by habamax** [comment]
Welcome!
