### ISSUE TITLE
Please set commentstring

### ISSUE THREAD

**Issue by anntzer** [habamax/vim-rst#8]
Various plugins (e.g. https://github.com/tomtom/tcomment_vim) use the `commentstring` setting to comment/uncomment lines, but currently vim-rst inherits the default commentstring (`/*%s*/`).  Please set it to `..\ %s`, as done in vim-restructuredtext.
Thanks :)

**Comment by habamax** [comment]
I actually had it initially, but then after using it a bit I found out it just not that helpful, comparing to, say, asciidoc.

Whatever you comment might be a comment or not in the end. Or even do not what you expect as with:


    .. note:: some note

after you try to comment it -- it would just remove leading dots.

Anyway I will add it.

PS, I was thinking to introduce 'special' vim-commentary like mappings to do rst-aware commenting but it is deep in backlog.
